<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Expense Breakdown - {{ $month }}</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f9fafb; color: #1f2937; padding: 20px;">
    <div style="max-width: 600px; margin: auto; background-color: #ffffff; padding: 24px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.05);">
        <h2 style="color: #4f46e5;">Expense Breakdown for {{ $month }}</h2>

        <p style="margin-bottom: 16px;">Hello <strong>{{ $name }}</strong>,</p>

        <p style="margin-bottom: 16px;">Here's your monthly summary by category. Keeping track of your spending is a great way to stay on top of your finances!</p>

        <table width="100%" cellpadding="10" cellspacing="0" border="1" style="border-collapse: collapse; margin-top: 16px;">
            <thead style="background-color: #e0e7ff;">
                <tr>
                    <th align="left" style="border-bottom: 2px solid #c7d2fe;">Category</th>
                    <th align="right" style="border-bottom: 2px solid #c7d2fe;">Amount (RM)</th>
                    <th align="right" style="border-bottom: 2px solid #c7d2fe;">Percentage</th>
                </tr>
            </thead>
            <tbody>
                @php $total = $categoryTotals->sum(); @endphp
                @foreach ($categoryTotals as $category => $amount)
                    <tr>
                        <td style="border-top: 1px solid #e5e7eb;">{{ $category }}</td>
                        <td align="right" style="border-top: 1px solid #e5e7eb;">{{ number_format($amount, 2) }}</td>
                        <td align="right" style="border-top: 1px solid #e5e7eb;">
                            {{ number_format(($amount / $total) * 100, 1) }}%
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <p style="margin-top: 20px; font-size: 16px;">
            <strong>Total Spent: RM {{ number_format($total, 2) }}</strong>
        </p>

        <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">

        <p style="color: #6b7280;">This report was automatically generated by your Expense Tracker account.</p>

        <p style="margin-top: 24px;">Best regards,<br><strong>Expense Tracker Team</strong></p>
    </div>
</body>
</html>
